### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by GangLiTarheel** [softmin/ReHLine-SVM#1]
Nice work! Can it handle 1 million samples with 2k or 20k features? Do you foresee any limitations if I use the Python version for this task?

**Comment by yixuan** [comment]
Just did a quick test using the [epsilon](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary.html#epsilon) data from the [LibSVM Data repository](https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/). The data set has 400,000 observations and 2000 features, smaller than your scenario but still at the same scale. The raw text file size is about 11.3 GB.

Running Liblinear with the options `./run_liblinear -s 3 -c 0.0025 -e 1e-5 epsilon_normalized` gives the following output:

```
*** Reading data... ***
*** Finished in 88.843304 seconds. ***

..*
optimization finished, #iter = 22
Objective value = -727.591521
nSV = 348485
Computation time: 6.341663 seconds.
```

And running ReHLine-SVM using the same parameters gives the following:

```
*** Use data file "epsilon_normalized" ***

*** Determining data dimension... ***
nrow = 400000, ncol = 2000
*** Finished in 1.43208 seconds. ***

*** Reading data... ***
*** Finished in 69.7734 seconds. ***

Iter 0, dual_objfn = -721.237, primal_objfn = 730.609, xi_diff = 0, beta_diff = 8.26269
*** Iter 9, free variables converge; next test on all variables
Computation time: 3.97393 seconds

objfn = 727.592

objfn(liblinear) = 727.592
```

The Python version is a simple wrapper of the C++ backend, and the difference should be small with large data sets.
